# Generated by VisualKernel [http://visualkernel.com/].
# Use VisualKernel Project Properties to edit.

KERNEL_MODULE_NAME := kgdboe
KERNEL_MODULE_OBJECT_FILE_LIST := irqsync.o kgdboe_main.o kgdboe_io.o nethook.o netpoll_wrapper.o poll_copy.o spinhook.o timerhook.o

obj-m := $(KERNEL_MODULE_NAME).o
$(KERNEL_MODULE_NAME)-y += $(KERNEL_MODULE_OBJECT_FILE_LIST)
ccflags-y := -ggdb -Og -std=gnu99

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

install:
	@echo "Installing $(KERNEL_MODULE_NAME).ko for initramfs startup"
	@chmod +x ./install_kgdboe.sh
	@./install_kgdboe.sh

